spring.application.name=url-shortener

spring.datasource.url = jdbc:postgresql://localhost:5432/urlshortenerdb
spring.datasource.username = postgres
spring.datasource.password = 1234
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect


spring.app.jwtExpirationMs = 172800000
spring.app.jwtSecret = hygSmC1k552sfwGpml28jbjSA6F4yl6PkTVjauXbEym
